import { useEffect, useState } from 'react';
import { api } from '../../api';
import ScheduleDialog from '../../components/ScheduleDialog';
import '../accounts.css';
const empty={name:'',brand:'',description:'',price:'',stock:0,is_active:1};
export default function AdminProducts(){
 const [rows,setRows]=useState([]),[form,setForm]=useState(null),[error,setError]=useState(''),[formError,setFormError]=useState(''),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[search,setSearch]=useState('');
 const load=async()=>{const d=await api.products();setRows(d.products);};
 useEffect(()=>{let live=true;api.products().then(d=>{if(live)setRows(d.products);}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[]);
 const edit=p=>{setForm({...p});setFormError('');};
 const submit=async e=>{e.preventDefault();setFormError('');setBusy(true);try{await api.saveProduct(form.id,form);setForm(null);setSuccess('Product saved.');await load();}catch(e){setFormError(e.message);setError(e.message);}finally{setBusy(false);}};
 const mutate=async(p,remove)=>{if(remove&&!window.confirm(`Permanently delete ${p.name}? Use Remove from sale to keep the record instead.`))return;setBusy(true);setError('');try{if(remove)await api.deleteProduct(p.id,p.version);else await api.saveProduct(p.id,{...p,is_active:Number(p.is_active)?0:1});setSuccess(remove?'Product deleted.':'Availability updated.');await load();}catch(e){setError(e.message);}finally{setBusy(false);}};
 const visible=rows.filter(p=>(p.name+' '+p.brand).toLowerCase().includes(search.toLowerCase()));
 return <main className="main"><div className="page-heading"><div><span className="eyebrow">Shop products</span><h1>Products</h1><p>Manage products for sale, descriptions and stock on hand.</p></div><button className="btn btn-primary" disabled={busy} onClick={()=>edit(empty)}>Add product</button></div>{error&&<div className="alert alert-error" role="alert">{error}</div>}{success&&<div className="alert alert-success" role="status">{success}</div>}<div className="card"><label className="form-row">Search products<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search Kahf, Gatsby or product name"/></label><p>{rows.length} products · {rows.reduce((n,p)=>n+Number(p.stock),0)} units in stock</p></div>{loading?<p>Loading products…</p>:<div className="product-grid">{visible.map(p=><article className="card product-card" key={p.id}><span className="product-brand">{p.brand}</span><h2>{p.name}</h2><p>{p.description||'No description added.'}</p><strong>RM {Number(p.price).toFixed(2)}</strong><p className="product-stock">{p.stock} left</p><small>{!Number(p.is_active)?'Removed from sale':Number(p.stock)===0?'Out of stock':'Available for sale'}</small><div className="product-actions"><button className="btn btn-outline" disabled={busy} onClick={()=>edit(p)}>Edit</button><button className="btn btn-outline" disabled={busy} onClick={()=>mutate(p,false)}>{Number(p.is_active)?'Remove from sale':'Restore to sale'}</button><button className="btn btn-danger-soft" disabled={busy} onClick={()=>mutate(p,true)}>Delete</button></div></article>)}</div>}{!loading&&!visible.length&&<div className="card empty-state">No products found. Add your shop’s first product.</div>}
 {form&&<ScheduleDialog title={form.id?'Edit product':'Add product'} busy={busy} onClose={()=>{if(!busy)setForm(null);}}><form onSubmit={submit}><div className="registration-body"><fieldset disabled={busy} style={{border:0,padding:0,minWidth:0}}>{formError&&<div className="alert alert-error" role="alert">{formError}</div>}<p>Start with a reference, then enter your shop’s actual details, price and stock.</p><div className="product-actions"><button type="button" className="btn btn-outline" onClick={()=>setForm(f=>({...f,brand:'Kahf',name:'Kahf Pomade'}))}>Kahf reference</button><button type="button" className="btn btn-outline" onClick={()=>setForm(f=>({...f,brand:'Gatsby',name:'Gatsby Moving Rubber Spiky Edge'}))}>Gatsby reference</button></div><div className="form-grid">{[['name','Product name',120],['brand','Brand',80]].map(([key,label,max])=><label key={key} className="form-row">{label} *<input required maxLength={max} value={form[key]} onChange={e=>setForm(f=>({...f,[key]:e.target.value}))}/></label>)}<label className="form-row">Price (RM) *<input type="number" min="0.01" max="999999.99" step="0.01" required value={form.price} onChange={e=>setForm(f=>({...f,price:e.target.value}))}/></label><label className="form-row">Stock remaining *<input type="number" min="0" max="1000000" step="1" required value={form.stock} onChange={e=>setForm(f=>({...f,stock:e.target.value}))}/></label><label className="form-row field-wide">Description<textarea rows={4} maxLength={2000} value={form.description||''} onChange={e=>setForm(f=>({...f,description:e.target.value}))}/></label><label className="form-row">Availability<select value={form.is_active} onChange={e=>setForm(f=>({...f,is_active:Number(e.target.value)}))}><option value={1}>For sale</option><option value={0}>Removed from sale</option></select></label></div></fieldset></div><div className="registration-footer"><button type="button" className="btn btn-outline" disabled={busy} onClick={()=>setForm(null)}>Cancel</button><button className="btn btn-primary" disabled={busy}>{busy?'Saving…':'Save product'}</button></div></form></ScheduleDialog>}</main>;
}
