import { useEffect, useState } from 'react';
import { api } from '../../api';
import '../../pages/accounts.css';
const empty={name:'',display_name:'',email:'',phone:'',password:'',password_confirmation:'',current_password:''};
export default function AdminAccounts(){
 const [rows,setRows]=useState(null),[form,setForm]=useState(empty),[error,setError]=useState(''),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let live=true;api.admins().then(d=>{if(live)setRows(d.admins);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[]);
 const submit=async e=>{e.preventDefault();setError('');setSuccess('');if(form.password!==form.password_confirmation){setError('Passwords do not match.');return;}setBusy(true);try{await api.createAdmin(form);setForm(empty);setSuccess('Admin registered. They can sign in, but cannot register other admins.');const d=await api.admins();setRows(d.admins);}catch(e){setError(e.message);}finally{setBusy(false);}};
 return <main className="main"><span className="eyebrow">Owner permission</span><h1>Manage Admins</h1><p>Only the original owner can register another admin. New admins do not receive owner permission.</p>{error&&<div role="alert" className="alert alert-error">{error}</div>}{success&&<div role="status" className="alert alert-success">{success}</div>}{rows&&<><form className="card account-form" onSubmit={submit}><h2>Register admin</h2><fieldset disabled={busy}><div className="form-grid">{[['name','Name','text',true,120],['display_name','Display name','text',false,120],['email','Email','email',true,160],['phone','Phone number','tel',false,30],['password','New admin password','password',true,72],['password_confirmation','Confirm new admin password','password',true,72],['current_password','Your owner password','password',true,200]].map(([key,label,type,required,max])=><label className="form-row" key={key}>{label}{required?' *':''}<input name={key} type={type} required={required} maxLength={max} minLength={key==='password'?8:undefined} autoComplete={type==='password'?(key==='current_password'?'current-password':'new-password'):undefined} value={form[key]} onChange={e=>setForm(f=>({...f,[key]:e.target.value}))}/></label>)}</div><button className="btn btn-primary">{busy?'Registering…':'Register admin'}</button></fieldset></form><section className="card"><h2>Admin accounts</h2><div className="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Phone</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.email}</td><td>{r.phone||'—'}</td><td>{Number(r.is_active)?'Active':'Inactive'}</td></tr>)}</tbody></table></div></section></>}</main>;
}
